apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appweb.fullname" }}-configmap
data:
  {{- tpl ((.Files.Glob "config/*.tmpl").AsConfig) . | nindent 2 }}

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ include "appweb.fullname" }}-configmap
# data:
#   #  aws_access_key_id: {{ .Values.configs.aws_access_key_id }}
#   #  aws_secret_access_key: {{ .Values.configs.aws_secret_access_key }}
#   {{- tpl ((.Files.Glob "config/*.tmpl").AsConfig) . | nindent 2 }}