apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appweb.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "appweb.labels" . | nindent 4 }}
data:
  aws_access_key_id_A:  {{ .Values.aws_access_key_id }}
  aws_secret_access_key_A: {{ .Values.aws_secret_access_key }}