apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appweb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appweb.labels" . | nindent 4 }}
type: Opaque
data:
  aws_access_key_id:  {{ .Values.aws_access_key_id | b64enc | quote }}
  aws_secret_access_key: {{ .Values.aws_secret_access_key | b64enc | quote }}